VERSION_DESCRIPTION: neighbors 2.0 dev

RAILS_VERSION: 2.3.12

NEIGHBORHOOD: 'highland_park'

BANNER_TITLE: Highland Park Neighbors
GUIDE_TITLE: 'Highland Park<br/>Emergency<br/>Preparedness<br/>Guide'
SITE_URL: highlandpark.nextdoorneighbors.org

WIKI_URL: http://wiki.nextdoorneighbors.org
FORUM_URL: http://greenwood-streetscapes-forum.1046493.n5.nabble.com/
BLOG_URL: blog.streetscapes.org

#MAPSERVER_URL: http://mapserver.streetscapes.org/cgi-bin/mapserv?map=/home/paul/mapserver/field_day_maps.map
MAPSERVER_URL: http://localhost/cgi-bin/mapserv?map=/home/paul/mapserver/



# put this in: config/initializers/load_config.rb
# APP_CONFIG = YAML.load_file("#{RAILS_ROOT}/config/config.yml")[RAILS_ENV]

# example usage:

# application.rb
# def authenticate
#  if APP_CONFIG['perform_authentication']
#    authenticate_or_request_with_http_basic do |username, password|
#      username == APP_CONFIG['username'] && password == APP_CONFIG['password']
#    end
#  end
# end
