MAPSERVER_DEBUG_LEVEL: 5
SITE_URL:              'http://maps.artpluslogic.com'
MAPSERVER_URL:         'http://mapserver.artpluslogic.com/cgi-bin/mapserv?map=/home/paul/mapserver/'
MAPSERVER_SYMBOL_FILE: "/home/paul/mapserver/symbols/simple_symbols.txt"
MAPSERVER_FONTS_FILE:  "/home/paul/mapserver/fonts/fonts.txt"
MAPSERVER_DIRECTORY:   '/home/paul/mapserver/'
MAPSERVER_PROJECTION:  'init=epsg:3857'
DB_NAME:               'neighbors_maps_dev'
DB_USERNAME:           'paul'
DB_PASSWORD:           '874rghtic'

NEIGHBORHOOD: 'Greenwood'
BANNER_TITLE:  Walking Greenwood 
GUIDE_TITLE:  'Highland Park<br/>Emergency<br/>Preparedness<br/>Guide'


WIKI_URL:     http://wiki.nextdoorneighbors.org
FORUM_URL:    http://greenwood-streetscapes-forum.1046493.n5.nabble.com/
BLOG_URL:     blog.streetscapes.org


# put this in: config/initializers/load_config.rb
# APP_CONFIG = YAML.load_file("#{RAILS_ROOT}/config/config.yml")[RAILS_ENV]

# example usage:

# application.rb
# def authenticate
#  if APP_CONFIG['perform_authentication']
#    authenticate_or_request_with_http_basic do |username, password|
#      username == APP_CONFIG['username'] && password == APP_CONFIG['password']
#    end
#  end
# end
