require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Ol3VectorStylesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Ol3VectorStyle. As you add validations to Ol3VectorStyle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Ol3VectorStylesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all ol3_vector_styles as @ol3_vector_styles" do
      ol3_vector_style = Ol3VectorStyle.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ol3_vector_styles)).to eq([ol3_vector_style])
    end
  end

  describe "GET #show" do
    it "assigns the requested ol3_vector_style as @ol3_vector_style" do
      ol3_vector_style = Ol3VectorStyle.create! valid_attributes
      get :show, {:id => ol3_vector_style.to_param}, valid_session
      expect(assigns(:ol3_vector_style)).to eq(ol3_vector_style)
    end
  end

  describe "GET #new" do
    it "assigns a new ol3_vector_style as @ol3_vector_style" do
      get :new, {}, valid_session
      expect(assigns(:ol3_vector_style)).to be_a_new(Ol3VectorStyle)
    end
  end

  describe "GET #edit" do
    it "assigns the requested ol3_vector_style as @ol3_vector_style" do
      ol3_vector_style = Ol3VectorStyle.create! valid_attributes
      get :edit, {:id => ol3_vector_style.to_param}, valid_session
      expect(assigns(:ol3_vector_style)).to eq(ol3_vector_style)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Ol3VectorStyle" do
        expect {
          post :create, {:ol3_vector_style => valid_attributes}, valid_session
        }.to change(Ol3VectorStyle, :count).by(1)
      end

      it "assigns a newly created ol3_vector_style as @ol3_vector_style" do
        post :create, {:ol3_vector_style => valid_attributes}, valid_session
        expect(assigns(:ol3_vector_style)).to be_a(Ol3VectorStyle)
        expect(assigns(:ol3_vector_style)).to be_persisted
      end

      it "redirects to the created ol3_vector_style" do
        post :create, {:ol3_vector_style => valid_attributes}, valid_session
        expect(response).to redirect_to(Ol3VectorStyle.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved ol3_vector_style as @ol3_vector_style" do
        post :create, {:ol3_vector_style => invalid_attributes}, valid_session
        expect(assigns(:ol3_vector_style)).to be_a_new(Ol3VectorStyle)
      end

      it "re-renders the 'new' template" do
        post :create, {:ol3_vector_style => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ol3_vector_style" do
        ol3_vector_style = Ol3VectorStyle.create! valid_attributes
        put :update, {:id => ol3_vector_style.to_param, :ol3_vector_style => new_attributes}, valid_session
        ol3_vector_style.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ol3_vector_style as @ol3_vector_style" do
        ol3_vector_style = Ol3VectorStyle.create! valid_attributes
        put :update, {:id => ol3_vector_style.to_param, :ol3_vector_style => valid_attributes}, valid_session
        expect(assigns(:ol3_vector_style)).to eq(ol3_vector_style)
      end

      it "redirects to the ol3_vector_style" do
        ol3_vector_style = Ol3VectorStyle.create! valid_attributes
        put :update, {:id => ol3_vector_style.to_param, :ol3_vector_style => valid_attributes}, valid_session
        expect(response).to redirect_to(ol3_vector_style)
      end
    end

    context "with invalid params" do
      it "assigns the ol3_vector_style as @ol3_vector_style" do
        ol3_vector_style = Ol3VectorStyle.create! valid_attributes
        put :update, {:id => ol3_vector_style.to_param, :ol3_vector_style => invalid_attributes}, valid_session
        expect(assigns(:ol3_vector_style)).to eq(ol3_vector_style)
      end

      it "re-renders the 'edit' template" do
        ol3_vector_style = Ol3VectorStyle.create! valid_attributes
        put :update, {:id => ol3_vector_style.to_param, :ol3_vector_style => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested ol3_vector_style" do
      ol3_vector_style = Ol3VectorStyle.create! valid_attributes
      expect {
        delete :destroy, {:id => ol3_vector_style.to_param}, valid_session
      }.to change(Ol3VectorStyle, :count).by(-1)
    end

    it "redirects to the ol3_vector_styles list" do
      ol3_vector_style = Ol3VectorStyle.create! valid_attributes
      delete :destroy, {:id => ol3_vector_style.to_param}, valid_session
      expect(response).to redirect_to(ol3_vector_styles_url)
    end
  end

end
